image: adoptopenjdk/openjdk11-openj9:alpine

variables:
  GRADLE_OPTS: "--no-daemon --console=plain"

before_script:
  - chmod +x gradlew

stages:
  - build
  - test
  - publish

  # We redirect the gradle user home using -g so that it caches the
  # wrapper and dependencies.
  # https://docs.gradle.org/current/userguide/gradle_command_line.html
  #
  # Unfortunately it also caches the build output so
  # cleaning removes reminants of any cached builds.
  # The assemble task actually builds the project.
  # If it fails here, the tests can't run.
build:
  stage: build
  script:
  - ./gradlew -g /cache/.gradle clean assemble
  allow_failure: false

test:
  stage: test
  script:
    - ./gradlew -g /cache/.gradle check
  allow_failure: false
  artifacts:
    when: on_failure
    paths:
      - build/reports
      - '*/build/reports'
    expire_in: 1 month

publish:
  stage: publish
  script:
    - ./gradlew -g /cache/.gradle publish
