name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Prepare environment
        run: chmod +x ./gradlew
      - name: Build and test using gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: --console=plain build
        env:
          API_KEY: ${{ secrets.TMDB_API_KEY }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests
          reporter: java-junit
          path: '**/TEST-*.xml'
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif
