name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build and test using gradle
        run: ./gradlew build
        env:
          API_KEY: ${{ secrets.TMDB_API_KEY }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests
          reporter: java-junit
          path: '**/TEST-*.xml'
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif
      - name: Archive logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-test-reports
          path: build/reports
