name: Deploy Kotlin Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Read library version
        id: version_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: ./gradle.properties
          properties: version
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build documentation
        run: ./gradlew dokkaHtmlMultiModule
      - name: Deploy 🚀
        if: ${{ !endsWith(steps.version_property.outputs.value, '-SNAPSHOT') }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/htmlMultiModule
