name: Deploy Kotlin Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Read library version
        id: version_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: ./gradle.properties
          property: version
      - name: Prepare environment
        run: chmod +x ./gradlew
      - name: Build documentation
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: --console=plain dokkaHtmlMultiModule
        env:
          GRADLE_OPTS: -Xmx4096m -XX:MaxPermSize=768m
      - name: Deploy 🚀
        # if: ${{ !endsWith(steps.version_property.outputs.value, '-SNAPSHOT') }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/htmlMultiModule
